"""Build comprehensive ATC catalog from consumption data + WHO classification."""
import json, sys, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))

# Load consumption data to extract ATC codes
d = json.load(open("frontend/public/data/consumption.json", encoding="utf-8"))
atc_codes = set()
for r in d:
    code = r.get("atc_code")
    if code:
        atc_codes.add(code)

print(f"Unique ATC codes in data: {len(atc_codes)}")

# Comprehensive ATC dictionary (WHO ATC/DDD Index + known classifications)
ATC_NAMES = {
    # A - Alimentary tract and metabolism
    "A": "Sistema digestivo y metabolismo",
    "A01": "Preparados estomatológicos",
    "A01A": "Preparados estomatológicos",
    "A01AB": "Antiinfecciosos para tratamiento oral",
    "A01AD": "Otros preparados estomatológicos",
    "A02": "Antiácidos y antiulcerosos",
    "A02A": "Antiácidos",
    "A02B": "Antiulcerosos",
    "A02BA": "Antagonistas H2",
    "A02BC": "Inhibidores de la bomba de protones",
    "A02BD": "Combinaciones para erradicar H. pylori",
    "A02BX": "Otros antiulcerosos",
    "A03": "Antiespasmódicos y procinéticos",
    "A03A": "Antiespasmódicos",
    "A03AA": "Anticolinérgicos sintéticos",
    "A03AX": "Otros antiespasmódicos",
    "A03B": "Procinéticos",
    "A03BA": "Alcaloides de la belladona",
    "A03BB": "Alcaloides semisintéticos de la belladona",
    "A03F": "Procinéticos",
    "A03FA": "Procinéticos",
    "A04": "Antieméticos",
    "A04A": "Antieméticos",
    "A04AA": "Setrones (antagonistas 5-HT3)",
    "A06": "Laxantes",
    "A06A": "Laxantes",
    "A06AB": "Laxantes de contacto",
    "A06AD": "Laxantes osmóticos",
    "A07": "Antidiarreicos",
    "A07A": "Antiinfecciosos intestinales",
    "A07AA": "Antibióticos intestinales",
    "A07D": "Inhibidores de la motilidad",
    "A07DA": "Inhibidores de la motilidad",
    "A07E": "Antiinflamatorios intestinales",
    "A07EC": "Ácido aminosalicílico",
    "A10": "Antidiabéticos",
    "A10A": "Insulinas",
    "A10AB": "Insulinas de acción rápida",
    "A10AC": "Insulinas de acción intermedia",
    "A10AD": "Insulinas de acción prolongada",
    "A10AE": "Insulinas de acción prolongada (nuevas)",
    "A10B": "Hipoglucemiantes orales",
    "A10BA": "Biguanidas (metformina)",
    "A10BB": "Sulfonilureas",
    "A10BD": "Combinaciones de hipoglucemiantes",
    "A10BG": "Tiazolidinedionas",
    "A10BH": "Inhibidores DPP-4 (gliptinas)",
    "A10BJ": "Agonistas GLP-1",
    "A10BK": "Inhibidores SGLT2 (gliflozinas)",
    "A10BX": "Otros hipoglucemiantes",
    "A11": "Vitaminas",
    "A11C": "Vitaminas A y D",
    "A11CC": "Vitamina D y análogos",
    "A11G": "Ácido ascórbico (vitamina C)",
    "A11H": "Otros preparados vitamínicos",
    "A12": "Suplementos minerales",
    "A12A": "Calcio",
    "A12AA": "Calcio",
    "A12AX": "Calcio con otros minerales",
    "A12B": "Potasio",
    "A12BA": "Potasio",
    "A12C": "Otros suplementos minerales",
    "A16": "Otros productos metabólicos",
    "A16A": "Otros productos metabólicos",
    "A16AB": "Enzimas",
    "A16AX": "Varios metabólicos",

    # B - Blood and blood forming organs
    "B": "Sangre y órganos hematopoyéticos",
    "B01": "Anticoagulantes y antiagregantes",
    "B01A": "Anticoagulantes",
    "B01AA": "Antagonistas de la vitamina K",
    "B01AB": "Heparinas",
    "B01AC": "Antiagregantes plaquetarios",
    "B01AE": "Inhibidores directos de trombina",
    "B01AF": "Inhibidores del factor Xa (DOACs)",
    "B02": "Antihemorrágicos",
    "B02B": "Vitamina K",
    "B02BA": "Vitamina K",
    "B02BB": "Fibrinógeno",
    "B02BD": "Factores de coagulación",
    "B03": "Antianémicos",
    "B03A": "Preparados de hierro",
    "B03AA": "Hierro oral",
    "B03AB": "Hierro parenteral",
    "B03B": "Vitamina B12 y ácido fólico",
    "B03BA": "Vitamina B12",
    "B03BB": "Ácido fólico",
    "B03X": "Otros antianémicos",
    "B03XA": "Eritropoyetinas",
    "B05": "Sustitutos del plasma",
    "B05B": "Soluciones intravenosas",
    "B05BA": "Soluciones para nutrición parenteral",
    "B05BB": "Soluciones electrolíticas",
    "B05C": "Soluciones para irrigación",
    "B05D": "Soluciones para diálisis",
    "B05X": "Aditivos para soluciones IV",
    "B05XA": "Soluciones de electrolitos",
    "B05XB": "Aminoácidos",

    # C - Cardiovascular system
    "C": "Sistema cardiovascular",
    "C01": "Terapia cardíaca",
    "C01A": "Glucósidos cardíacos",
    "C01AA": "Digitálicos",
    "C01B": "Antiarrítmicos clase I y III",
    "C01BA": "Antiarrítmicos clase Ia",
    "C01BB": "Antiarrítmicos clase Ib",
    "C01BC": "Antiarrítmicos clase Ic",
    "C01BD": "Antiarrítmicos clase III",
    "C01C": "Estimulantes cardíacos",
    "C01CA": "Adrenérgicos y dopaminérgicos",
    "C01D": "Vasodilatadores cardíacos",
    "C01DA": "Nitratos orgánicos",
    "C01E": "Otros preparados cardíacos",
    "C01EB": "Ivabradina",
    "C02": "Antihipertensivos",
    "C02A": "Antiadrenérgicos centrales",
    "C02AB": "Metildopa",
    "C02C": "Antiadrenérgicos periféricos",
    "C02CA": "Alfabloqueantes",
    "C02D": "Vasodilatadores arteriales",
    "C02K": "Otros antihipertensivos",
    "C02KX": "Antihipertensivos para HTP",
    "C03": "Diuréticos",
    "C03A": "Tiazidas",
    "C03AA": "Tiazidas simples",
    "C03B": "Diuréticos de techo bajo",
    "C03BA": "Sulfonamidas",
    "C03C": "Diuréticos de techo alto",
    "C03CA": "Sulfonamidas de techo alto",
    "C03D": "Ahorradores de potasio",
    "C03DA": "Antagonistas de aldosterona",
    "C03E": "Combinaciones de diuréticos",
    "C04": "Vasodilatadores periféricos",
    "C04A": "Vasodilatadores periféricos",
    "C05": "Protectores capilares",
    "C05C": "Fármacos estabilizadores capilares",
    "C05CA": "Bioflavonoides",
    "C07": "Betabloqueantes",
    "C07A": "Betabloqueantes",
    "C07AA": "Betabloqueantes no selectivos",
    "C07AB": "Betabloqueantes selectivos",
    "C07AG": "Alfa y betabloqueantes",
    "C08": "Calcioantagonistas",
    "C08C": "Calcioantagonistas selectivos vasculares",
    "C08CA": "Dihidropiridinas",
    "C08D": "Calcioantagonistas selectivos cardíacos",
    "C08DA": "Verapamilo y derivados",
    "C09": "IECA y ARA-II",
    "C09A": "IECA solos",
    "C09AA": "IECA",
    "C09B": "IECA combinados",
    "C09BA": "IECA + diuréticos",
    "C09BB": "IECA + calcioantagonistas",
    "C09C": "ARA-II solos",
    "C09CA": "ARA-II",
    "C09D": "ARA-II combinados",
    "C09DA": "ARA-II + diuréticos",
    "C09DB": "ARA-II + calcioantagonistas",
    "C09DX": "Otras combinaciones con ARA-II",
    "C10": "Hipolipemiantes",
    "C10A": "Hipolipemiantes solos",
    "C10AA": "Estatinas",
    "C10AB": "Fibratos",
    "C10AC": "Secuestradores de ácidos biliares",
    "C10AD": "Ácido nicotínico",
    "C10AX": "Otros hipolipemiantes",

    # D - Dermatologicals
    "D": "Dermatológicos",
    "D01": "Antifúngicos tópicos",
    "D01A": "Antifúngicos tópicos",
    "D01AC": "Derivados imidazólicos",
    "D01AE": "Otros antifúngicos tópicos",
    "D02": "Emolientes y protectores",
    "D02A": "Emolientes y protectores",
    "D04": "Antipruriginosos",
    "D04A": "Antipruriginosos",
    "D05": "Antipsoriásicos",
    "D05A": "Antipsoriásicos tópicos",
    "D05AX": "Otros antipsoriásicos tópicos",
    "D05B": "Antipsoriásicos sistémicos",
    "D05BB": "Retinoides para psoriasis",
    "D06": "Antibióticos y quimioterápicos tópicos",
    "D06A": "Antibióticos tópicos",
    "D06AX": "Otros antibióticos tópicos",
    "D07": "Corticosteroides tópicos",
    "D07A": "Corticosteroides tópicos solos",
    "D07AC": "Corticosteroides potentes (grupo III)",
    "D07AD": "Corticosteroides muy potentes (grupo IV)",
    "D07X": "Combinaciones con corticosteroides",
    "D10": "Anti-acné",
    "D10A": "Anti-acné tópicos",
    "D10AD": "Retinoides tópicos",
    "D10AE": "Peróxido de benzoilo",
    "D10AF": "Antiinfecciosos para acné",
    "D10B": "Anti-acné sistémicos",
    "D10BA": "Retinoides sistémicos",
    "D11": "Otros preparados dermatológicos",
    "D11A": "Otros preparados dermatológicos",
    "D11AX": "Otros dermatológicos",

    # G - Genito-urinary system and sex hormones
    "G": "Sistema genitourinario y hormonas sexuales",
    "G01": "Antiinfecciosos ginecológicos",
    "G01A": "Antiinfecciosos ginecológicos",
    "G01AF": "Derivados imidazólicos",
    "G02": "Otros preparados ginecológicos",
    "G02A": "Uterotónicos",
    "G02B": "Anticonceptivos tópicos",
    "G02C": "Otros ginecológicos",
    "G02CA": "Simpaticomiméticos (tocolíticos)",
    "G02CB": "Inhibidores de prolactina",
    "G03": "Hormonas sexuales",
    "G03A": "Anticonceptivos sistémicos",
    "G03AA": "Combinaciones de estrógenos y progestágenos",
    "G03C": "Estrógenos",
    "G03CA": "Estrógenos naturales",
    "G03D": "Progestágenos",
    "G03DA": "Derivados de la pregnen(4)",
    "G03G": "Gonadotropinas",
    "G03GA": "Gonadotropinas",
    "G03H": "Antiandrógenos",
    "G03HA": "Antiandrógenos",
    "G03HB": "Antiandrógenos + estrógenos",
    "G04": "Urológicos",
    "G04B": "Medicamentos urológicos",
    "G04BD": "Antiespasmódicos urinarios",
    "G04BE": "Inhibidores PDE5 (disfunción eréctil)",
    "G04C": "Tratamiento HBP",
    "G04CA": "Alfabloqueantes para HBP",
    "G04CB": "Inhibidores 5-alfa reductasa",

    # H - Systemic hormones (excl. sex hormones)
    "H": "Hormonas sistémicas (excl. sexuales)",
    "H01": "Hormonas hipofisarias e hipotalámicas",
    "H01A": "Hormonas del lóbulo anterior de la hipófisis",
    "H01AC": "Somatropina (GH)",
    "H01B": "Oxitocina y análogos",
    "H01BB": "Oxitocina y análogos",
    "H02": "Corticosteroides sistémicos",
    "H02A": "Corticosteroides sistémicos solos",
    "H02AB": "Glucocorticoides",
    "H03": "Hormonas tiroideas",
    "H03A": "Hormonas tiroideas",
    "H03AA": "Hormonas tiroideas (levotiroxina)",
    "H03B": "Antitiroideos",
    "H03BB": "Derivados de la tiourea",
    "H04": "Hormonas pancreáticas",
    "H04A": "Glucagón",
    "H04AA": "Glucagón",
    "H05": "Homeostasis del calcio",
    "H05B": "Antiparatiroideos",
    "H05BA": "Calcitonina",
    "H05BX": "Otros antiparatiroideos (cinacalcet)",

    # J - Antiinfectives for systemic use
    "J": "Antiinfecciosos sistémicos",
    "J01": "Antibacterianos sistémicos",
    "J01A": "Tetraciclinas",
    "J01AA": "Tetraciclinas",
    "J01B": "Anfenicoles",
    "J01BA": "Anfenicoles",
    "J01C": "Penicilinas",
    "J01CA": "Penicilinas de amplio espectro",
    "J01CE": "Penicilinas sensibles a betalactamasas",
    "J01CF": "Penicilinas resistentes a betalactamasas",
    "J01CR": "Combinaciones de penicilinas",
    "J01D": "Cefalosporinas y otros betalactámicos",
    "J01DB": "Cefalosporinas de primera generación",
    "J01DC": "Cefalosporinas de segunda generación",
    "J01DD": "Cefalosporinas de tercera generación",
    "J01DE": "Cefalosporinas de cuarta generación",
    "J01DH": "Carbapenems",
    "J01DI": "Otras cefalosporinas y penems",
    "J01E": "Sulfonamidas y trimetoprima",
    "J01EA": "Trimetoprima y derivados",
    "J01EE": "Combinaciones de sulfonamidas",
    "J01F": "Macrólidos y lincosamidas",
    "J01FA": "Macrólidos",
    "J01FF": "Lincosamidas",
    "J01FG": "Estreptograminas",
    "J01G": "Aminoglucósidos",
    "J01GA": "Estreptomicinas",
    "J01GB": "Otros aminoglucósidos",
    "J01M": "Quinolonas",
    "J01MA": "Fluoroquinolonas",
    "J01MB": "Otras quinolonas",
    "J01X": "Otros antibacterianos",
    "J01XA": "Glucopéptidos",
    "J01XB": "Polimixinas",
    "J01XC": "Antibacterianos esteroideos",
    "J01XD": "Derivados imidazólicos",
    "J01XE": "Nitrofuranos",
    "J01XX": "Otros antibacterianos",
    "J02": "Antifúngicos sistémicos",
    "J02A": "Antifúngicos sistémicos",
    "J02AA": "Antibióticos antifúngicos",
    "J02AC": "Triazoles",
    "J02AX": "Otros antifúngicos sistémicos",
    "J04": "Antimicobacterianos",
    "J04A": "Antituberculosos",
    "J04AB": "Antibióticos antituberculosos",
    "J04AC": "Hidrazidas",
    "J04AK": "Combinaciones antituberculosas",
    "J04B": "Antileprosos",
    "J04BA": "Antileprosos",
    "J05": "Antivirales sistémicos",
    "J05A": "Antivirales de acción directa",
    "J05AB": "Nucleósidos/nucleótidos (excl. VIH)",
    "J05AE": "Inhibidores de la proteasa (VHC)",
    "J05AF": "Nucleósidos/nucleótidos para VIH",
    "J05AG": "No nucleósidos para VIH",
    "J05AH": "Inhibidores de neuraminidasa (gripe)",
    "J05AJ": "Inhibidores de la integrasa (VIH)",
    "J05AR": "Combinaciones antivirales para VIH/VHC",
    "J06": "Inmunoglobulinas y sueros",
    "J06B": "Inmunoglobulinas inespecíficas",
    "J06BA": "Inmunoglobulinas humanas",
    "J06BB": "Inmunoglobulinas específicas",
    "J07": "Vacunas",
    "J07A": "Vacunas bacterianas",
    "J07AE": "Vacuna antimeningocócica",
    "J07AG": "Vacuna anti-Haemophilus influenzae B",
    "J07AJ": "Vacuna anticolérica",
    "J07AL": "Vacuna antineumocócica",
    "J07AM": "Vacuna antitetánica",
    "J07B": "Vacunas virales",
    "J07BB": "Vacuna antigripal",
    "J07BC": "Vacuna antihepatitis A/B",
    "J07BD": "Vacuna antisarampionosa",
    "J07BE": "Vacuna antiparotiditis",
    "J07BF": "Vacuna antipoliomielítica",
    "J07BH": "Vacuna anti-COVID-19",
    "J07BM": "Vacuna VPH",
    "J07BX": "Otras vacunas virales",
    "J07C": "Vacunas bacterianas y virales combinadas",

    # L - Antineoplastic and immunomodulating agents
    "L": "Antineoplásicos e inmunomoduladores",
    "L01": "Antineoplásicos",
    "L01A": "Agentes alquilantes",
    "L01AA": "Mostazas nitrogenadas",
    "L01B": "Antimetabolitos",
    "L01BA": "Análogos del ácido fólico",
    "L01BB": "Análogos de purinas",
    "L01BC": "Análogos de pirimidinas",
    "L01C": "Alcaloides y productos naturales",
    "L01CA": "Alcaloides de la vinca",
    "L01CB": "Podofilotoxinas",
    "L01CD": "Taxanos",
    "L01D": "Antibióticos citotóxicos",
    "L01DB": "Antraciclinas",
    "L01DC": "Otros antibióticos citotóxicos",
    "L01E": "Inhibidores de proteína kinasa",
    "L01EA": "Inhibidores BCR-ABL",
    "L01EB": "Inhibidores EGFR",
    "L01EC": "Inhibidores BRAF",
    "L01ED": "Inhibidores ALK",
    "L01EE": "Inhibidores MEK",
    "L01EF": "Inhibidores CDK",
    "L01EG": "Inhibidores mTOR",
    "L01EL": "Inhibidores BTK",
    "L01EM": "Inhibidores PI3K",
    "L01EX": "Otros inhibidores de proteína kinasa",
    "L01F": "Anticuerpos monoclonales",
    "L01FA": "Anticuerpos anti-CD20",
    "L01FC": "Anticuerpos anti-HER2",
    "L01FD": "Anticuerpos anti-EGFR",
    "L01FE": "Anticuerpos anti-VEGF",
    "L01FF": "Anticuerpos anti-PD1/PDL1",
    "L01FX": "Otros anticuerpos monoclonales",
    "L01X": "Otros antineoplásicos",
    "L01XA": "Compuestos de platino",
    "L01XB": "Metilhidrazinas",
    "L01XC": "Anticuerpos conjugados",
    "L01XX": "Otros agentes antineoplásicos",
    "L02": "Terapia endocrina",
    "L02A": "Hormonas y análogos",
    "L02AE": "Análogos de GnRH",
    "L02B": "Antagonistas hormonales",
    "L02BA": "Antiestrógenos",
    "L02BB": "Antiandrógenos",
    "L02BG": "Inhibidores de aromatasa",
    "L02BX": "Otros antagonistas hormonales",
    "L03": "Inmunoestimulantes",
    "L03A": "Factores de crecimiento",
    "L03AA": "Factores estimulantes de colonias",
    "L03AB": "Interferones",
    "L03AX": "Otros inmunoestimulantes",
    "L04": "Inmunosupresores",
    "L04A": "Inmunosupresores",
    "L04AA": "Inhibidores de calcineurina",
    "L04AB": "Inhibidores TNF-alfa",
    "L04AC": "Inhibidores IL",
    "L04AD": "Inhibidores JAK",
    "L04AX": "Otros inmunosupresores",

    # M - Musculo-skeletal system
    "M": "Sistema musculoesquelético",
    "M01": "Antiinflamatorios y antirreumáticos",
    "M01A": "AINEs no esteroideos",
    "M01AB": "Derivados del ácido acético (diclofenaco)",
    "M01AC": "Oxicams",
    "M01AE": "Derivados del ácido propiónico (ibuprofeno)",
    "M01AG": "Fenamatos",
    "M01AH": "Coxibs",
    "M01AX": "Otros AINEs",
    "M01B": "Combinaciones de AINEs",
    "M01C": "Fármacos antirreumáticos específicos",
    "M01CB": "Sales de oro",
    "M01CC": "Penicilamina",
    "M01CX": "Otros agentes antirreumáticos",
    "M02": "Analgésicos tópicos",
    "M02A": "Analgésicos tópicos",
    "M02AA": "AINEs tópicos",
    "M03": "Relajantes musculares",
    "M03B": "Relajantes musculares centrales",
    "M03BA": "Carbamatos",
    "M03BB": "Oxazoles, tiazinas y triazinas",
    "M03BX": "Otros relajantes centrales",
    "M04": "Antigotosos",
    "M04A": "Antigotosos",
    "M04AA": "Inhibidores de la síntesis de ácido úrico",
    "M04AB": "Uricosúricos",
    "M04AC": "Sin acción sobre el ácido úrico (colchicina)",
    "M05": "Tratamiento de enfermedades óseas",
    "M05B": "Bifosfonatos",
    "M05BA": "Bifosfonatos",
    "M05BB": "Bifosfonatos + vitamina D",
    "M05BX": "Otros tratamientos óseos (denosumab)",
    "M09": "Otros trastornos musculoesqueléticos",

    # N - Nervous system
    "N": "Sistema nervioso",
    "N01": "Anestésicos",
    "N01A": "Anestésicos generales",
    "N01AB": "Hidrocarburos halogenados",
    "N01AH": "Anestésicos opioides",
    "N01AX": "Otros anestésicos generales",
    "N01B": "Anestésicos locales",
    "N01BB": "Amidas",
    "N02": "Analgésicos",
    "N02A": "Opioides",
    "N02AA": "Alcaloides naturales del opio",
    "N02AB": "Derivados de la fenilpiperidina",
    "N02AE": "Derivados de la oripavina",
    "N02AX": "Otros opioides",
    "N02B": "Analgésicos no opioides",
    "N02BA": "Salicilatos",
    "N02BB": "Pirazolonas (metamizol)",
    "N02BE": "Anilidas (paracetamol)",
    "N02C": "Antimigrañosos",
    "N02CA": "Alcaloides del cornezuelo del centeno",
    "N02CC": "Agonistas selectivos 5-HT1 (triptanes)",
    "N02CX": "Otros antimigrañosos",
    "N03": "Antiepilépticos",
    "N03A": "Antiepilépticos",
    "N03AA": "Barbitúricos",
    "N03AB": "Hidantoínas",
    "N03AE": "Benzodiazepinas",
    "N03AF": "Carboxamidas",
    "N03AG": "Ácidos grasos (valproato)",
    "N03AX": "Otros antiepilépticos",
    "N04": "Antiparkinsonianos",
    "N04A": "Anticolinérgicos",
    "N04AA": "Aminas terciarias",
    "N04B": "Dopaminérgicos",
    "N04BA": "Dopa y derivados (levodopa)",
    "N04BC": "Agonistas dopaminérgicos",
    "N04BD": "Inhibidores MAO-B",
    "N04BX": "Otros dopaminérgicos",
    "N05": "Psicolépticos",
    "N05A": "Antipsicóticos",
    "N05AA": "Fenotiazinas alifáticas",
    "N05AB": "Fenotiazinas piperazínicas",
    "N05AD": "Butirofenonas",
    "N05AE": "Derivados del indol",
    "N05AF": "Derivados del tioxanteno",
    "N05AG": "Derivados de la difenilbutilpiperidina",
    "N05AH": "Diazepinas y oxazepinas (olanzapina)",
    "N05AL": "Benzamidas (sulpirida)",
    "N05AX": "Otros antipsicóticos",
    "N05B": "Ansiolíticos",
    "N05BA": "Benzodiazepinas",
    "N05BB": "Derivados del difenilmetano",
    "N05BC": "Carbamatos",
    "N05BE": "Azaspirodecanodionas (buspirona)",
    "N05C": "Hipnóticos y sedantes",
    "N05CD": "Benzodiazepinas hipnóticas",
    "N05CF": "Fármacos relacionados con benzodiazepinas (z-drugs)",
    "N05CH": "Agonistas del receptor de melatonina",
    "N05CM": "Otros hipnóticos y sedantes",
    "N06": "Psicoanalépticos",
    "N06A": "Antidepresivos",
    "N06AA": "Inhibidores no selectivos de recaptación de monoaminas (tricíclicos)",
    "N06AB": "ISRS",
    "N06AF": "IMAO no selectivos",
    "N06AG": "IMAO-A",
    "N06AX": "Otros antidepresivos",
    "N06B": "Psicoestimulantes y nootrópicos",
    "N06BA": "Simpaticomiméticos centrales",
    "N06BC": "Derivados de la xantina",
    "N06BX": "Otros psicoestimulantes",
    "N06D": "Antidemencia",
    "N06DA": "Inhibidores de la colinesterasa",
    "N06DX": "Otros fármacos antidemencia",
    "N07": "Otros fármacos del sistema nervioso",
    "N07A": "Parasimpaticomiméticos",
    "N07AA": "Anticolinesterásicos",
    "N07B": "Tratamiento de adicciones",
    "N07BA": "Tratamiento de la dependencia de nicotina",
    "N07BB": "Tratamiento de la dependencia de alcohol",
    "N07BC": "Tratamiento de la dependencia de opioides",
    "N07X": "Otros fármacos del sistema nervioso",
    "N07XX": "Otros (p. ej., riluzol)",

    # P - Antiparasitic products
    "P": "Antiparasitarios",
    "P01": "Antiprotozoarios",
    "P01A": "Contra amebiasis y otras protozoosis",
    "P01AB": "Derivados nitroimidazólicos",
    "P01B": "Antimaláricos",
    "P01BA": "Aminoquinolinas",
    "P01BB": "Biguanidas",
    "P01BC": "Metanolquinolinas",
    "P01BD": "Diaminopirimidinas",
    "P02": "Antihelmínticos",
    "P02B": "Antitrematodos",
    "P02BA": "Derivados de la quinolina",
    "P02C": "Antinematodos",
    "P02CA": "Derivados del benzimidazol",
    "P02CB": "Piperazina y derivados",
    "P02CC": "Derivados de la tetrahidropirimidina",
    "P02CE": "Derivados del imidazotiazol",
    "P02CF": "Avermectinas",
    "P03": "Ectoparasiticidas",
    "P03A": "Sarnicidas y pediculicidas",
    "P03AC": "Piretrinas",

    # R - Respiratory system
    "R": "Sistema respiratorio",
    "R01": "Descongestivos nasales",
    "R01A": "Simpaticomiméticos nasales",
    "R01AA": "Simpaticomiméticos nasales",
    "R01AD": "Corticosteroides nasales",
    "R02": "Preparados para la garganta",
    "R02A": "Preparados para la garganta",
    "R03": "Antiasmáticos y EPOC",
    "R03A": "Adrenérgicos inhalados",
    "R03AC": "Agonistas beta-2 selectivos de acción corta",
    "R03AK": "Combinaciones de adrenérgicos",
    "R03B": "Otros fármacos inhalados para EPOC/asma",
    "R03BA": "Corticosteroides inhalados",
    "R03BB": "Anticolinérgicos inhalados",
    "R03BC": "Cromonas inhaladas",
    "R03D": "Antileucotrienos",
    "R03DA": "Cisteinil-leucotrienos",
    "R03DC": "Antagonistas de leucotrienos",
    "R03DX": "Otros fármacos para asma",
    "R05": "Antitusivos y expectorantes",
    "R05C": "Expectorantes",
    "R05CA": "Mucolíticos",
    "R05CB": "Mucolíticos (acetilcisteína)",
    "R05D": "Antitusivos",
    "R05DA": "Alcaloides del opio",
    "R05DB": "Otros antitusivos",
    "R06": "Antihistamínicos sistémicos",
    "R06A": "Antihistamínicos sistémicos",
    "R06AA": "Aminoalquil éteres",
    "R06AB": "Alquilaminas sustituidas",
    "R06AC": "Etilendiaminas sustituidas",
    "R06AD": "Derivados de la fenotiazina",
    "R06AE": "Derivados de la piperazina",
    "R06AX": "Otros antihistamínicos",

    # S - Sensory organs
    "S": "Órganos de los sentidos",
    "S01": "Oftalmológicos",
    "S01A": "Antiinfecciosos oftálmicos",
    "S01AA": "Antibióticos oftálmicos",
    "S01AD": "Antivirales oftálmicos",
    "S01B": "Antiinflamatorios oftálmicos",
    "S01BA": "Corticosteroides oftálmicos",
    "S01BC": "AINEs oftálmicos",
    "S01E": "Antiglaucoma y mióticos",
    "S01EC": "Inhibidores de la anhidrasa carbónica",
    "S01ED": "Betabloqueantes oftálmicos",
    "S01EE": "Análogos de prostaglandinas",
    "S01F": "Midriáticos y ciclopléjicos",
    "S01FA": "Anticolinérgicos oftálmicos",
    "S01G": "Descongestivos y antialérgicos oftálmicos",
    "S01GX": "Otros antialérgicos oftálmicos",
    "S01H": "Anestésicos oftálmicos",
    "S01HA": "Anestésicos locales oftálmicos",
    "S01L": "Agentes antineovascularización ocular",
    "S01LA": "Anti-VEGF oftálmicos",
    "S01X": "Otros oftalmológicos",
    "S02": "Otológicos",
    "S02A": "Antiinfecciosos óticos",
    "S02AA": "Antibióticos óticos",
    "S02C": "Combinaciones con corticosteroides óticos",
    "S03": "Preparados oftalmológicos y otológicos",

    # V - Various
    "V": "Varios",
    "V01": "Alérgenos",
    "V01A": "Alérgenos",
    "V03": "Varios terapéuticos",
    "V03A": "Antídotos",
    "V03AB": "Antídotos",
    "V03AF": "Agentes desintoxicantes para citostáticos",
    "V04": "Agentes diagnósticos",
    "V04C": "Otros agentes diagnósticos",
    "V04CF": "Pruebas de tuberculina",
    "V06": "Nutrición general",
    "V06D": "Otros nutrientes",
    "V07": "Varios no terapéuticos",
    "V08": "Medios de contraste",
    "V08A": "Medios de contraste para rayos X",
    "V08AB": "Medios de contraste hidrosolubles nefrotrópicos",
    "V08B": "Medios de contraste para RMN",
    "V08BA": "Medios de contraste para RMN con gadolinio",
    "V08C": "Medios de contraste para ultrasonografía",
    "V09": "Radiofármacos",
    "V10": "Radiofármacos terapéuticos",
}

# Map ATC codes to active ingredients
ATC_DRUGS = {
    "A02BC": ["omeprazol", "pantoprazol", "esomeprazol", "lansoprazol", "rabeprazol"],
    "A10BA": ["metformina"],
    "A10BB": ["glibenclamida", "gliclazida", "glimepirida"],
    "A10BH": ["sitagliptina", "vildagliptina", "linagliptina"],
    "A10BJ": ["semaglutida", "liraglutida", "dulaglutida"],
    "A10BK": ["empagliflozina", "dapagliflozina", "canagliflozina"],
    "B01AA": ["acenocumarol", "warfarina"],
    "B01AC": ["clopidogrel", "prasugrel", "ticagrelor"],
    "B01AE": ["dabigatrán"],
    "B01AF": ["rivaroxabán", "apixabán", "edoxabán"],
    "C01AA": ["digoxina"],
    "C03CA": ["furosemida", "torasemida"],
    "C03DA": ["espironolactona", "eplerenona"],
    "C07AA": ["propranolol"],
    "C07AB": ["bisoprolol", "atenolol", "metoprolol", "carvedilol"],
    "C08CA": ["amlodipino", "nifedipino", "lercanidipino"],
    "C09AA": ["enalapril", "ramipril", "lisinopril", "captopril"],
    "C09CA": ["losartán", "valsartán", "irbesartán", "candesartán", "telmisartán"],
    "C10AA": ["atorvastatina", "simvastatina", "rosuvastatina", "pravastatina"],
    "G04CA": ["tamsulosina", "alfuzosina", "silodosina"],
    "G04CB": ["finasterida", "dutasterida"],
    "H02AB": ["prednisona", "metilprednisolona", "dexametasona", "hidrocortisona"],
    "H03AA": ["levotiroxina"],
    "J01CA": ["amoxicilina", "ampicilina"],
    "J01CE": ["fenoximetilpenicilina"],
    "J01CR": ["amoxicilina-clavulánico", "amoxicilina/ácido clavulánico"],
    "J01DD": ["ceftriaxona", "cefotaxima", "cefixima"],
    "J01EE": ["sulfametoxazol-trimetoprima"],
    "J01FA": ["azitromicina", "claritromicina", "eritromicina"],
    "J01FF": ["clindamicina"],
    "J01GB": ["gentamicina", "tobramicina", "amikacina"],
    "J01MA": ["ciprofloxacino", "levofloxacino", "moxifloxacino"],
    "J01XA": ["vancomicina"],
    "J01XD": ["metronidazol"],
    "J01XE": ["nitrofurantoína"],
    "J01XX": ["fosfomicina", "linezolid"],
    "J02AC": ["fluconazol", "itraconazol", "voriconazol"],
    "J05AB": ["aciclovir", "valaciclovir"],
    "J05AF": ["tenofovir", "emtricitabina", "lamivudina"],
    "J05AR": ["bictegravir-emtricitabina-tenofovir", "dolutegravir-lamivudina"],
    "L02BA": ["tamoxifeno"],
    "L02BG": ["letrozol", "anastrozol", "exemestano"],
    "L04AB": ["adalimumab", "infliximab", "etanercept"],
    "L04AX": ["metotrexato", "azatioprina", "micofenolato"],
    "M01AB": ["diclofenaco"],
    "M01AE": ["ibuprofeno", "naproxeno", "dexketoprofeno"],
    "M01AH": ["celecoxib", "etoricoxib"],
    "M04AA": ["alopurinol", "febuxostat"],
    "M05BA": ["alendronato", "risedronato", "ácido zoledrónico"],
    "N02AA": ["morfina", "oxicodona"],
    "N02AB": ["fentanilo"],
    "N02AX": ["tramadol", "tapentadol"],
    "N02BE": ["paracetamol"],
    "N02BB": ["metamizol"],
    "N03AX": ["gabapentina", "pregabalina", "levetiracetam", "lamotrigina", "topiramato"],
    "N04BA": ["levodopa-carbidopa"],
    "N05AH": ["olanzapina", "quetiapina", "clozapina"],
    "N05AX": ["risperidona", "paliperidona", "aripiprazol"],
    "N05BA": ["diazepam", "lorazepam", "alprazolam", "bromazepam", "clonazepam"],
    "N05CD": ["lormetazepam"],
    "N05CF": ["zolpidem", "zopiclona"],
    "N06AB": ["sertralina", "fluoxetina", "paroxetina", "citalopram", "escitalopram"],
    "N06AX": ["venlafaxina", "duloxetina", "mirtazapina", "trazodona", "vortioxetina"],
    "N06DA": ["donepezilo", "rivastigmina", "galantamina"],
    "R03AC": ["salbutamol", "terbutalina"],
    "R03AK": ["salmeterol-fluticasona"],
    "R03BA": ["budesonida", "fluticasona", "beclometasona"],
    "R03BB": ["ipratropio", "tiotropio"],
    "R03DC": ["montelukast"],
    "R06AX": ["cetirizina", "levocetirizina", "loratadina", "ebastina", "bilastina"],
    "S01EC": ["dorzolamida", "brinzolamida"],
    "S01ED": ["timolol"],
    "S01EE": ["latanoprost", "travoprost", "bimatoprost"],
    "S01LA": ["aflibercept", "ranibizumab"],
    "A06AD": ["movicol", "macrogol", "lactulosa"],
    "A07DA": ["loperamida"],
    "A07EC": ["mesalazina", "sulfasalazina"],
    "C02KX": ["bosentán", "ambrisentán", "sildenafilo (HTP)"],
    "C10AB": ["gemfibrozilo", "fenofibrato"],
    "L01XE": ["imatinib"],
    "L01XE": ["erlotinib", "gefitinib", "afatinib", "osimertinib"],
    "M01CX": ["hidroxicloroquina"],
    "N05CH": ["melatonina"],
    "R05CB": ["acetilcisteína"],
    "V03AB": ["naloxona", "flumazenilo"],
    "G04BE": ["sildenafilo", "tadalafilo", "vardenafilo"],
    "D10BA": ["isotretinoína"],
    "A11CC": ["colecalciferol", "calcitriol"],
    "B03BB": ["ácido fólico"],
    "B03XA": ["epoyetina alfa", "darbepoyetina"],
    "P01AB": ["metronidazol (antiparasitario)"],
    "A12AX": ["calcio + vitamina D"],
    "M01CC": ["penicilamina"],
}

# Build ATC codes list
new_atc = []
for code in sorted(atc_codes):
    name = ATC_NAMES.get(code, code)
    level = 1 + sum(1 for ch in code if ch.isalpha())
    parent = code[:-1] if code[-1].isalpha() else (code[:-2] if len(code) > 2 else None)
    new_atc.append({"code": code, "name": name, "level": level, "parent_code": parent})

# Build drugs list with ATC links
drugs_set = set()
atc_drug_links = []
for code, ingredients in ATC_DRUGS.items():
    if code in atc_codes:
        for ing in ingredients:
            normalized = ing.lower().replace(" ", "_").replace("/", "_")
            drugs_set.add((ing, ing))
            atc_drug_links.append((ing, code))

# Save to files
out = Path("data/processed/public")
out.mkdir(parents=True, exist_ok=True)

# Update ATC codes
with open(out / "atc.json", "w", encoding="utf-8") as f:
    json.dump(new_atc, f, ensure_ascii=False, indent=2)

# Update drugs
drugs_list = [{"id": i+1, "name": name, "active_ingredient": ai, "normalized_name": name.lower().replace(" ", "")} 
              for i, (name, ai) in enumerate(sorted(drugs_set))]
with open(out / "drugs.json", "w", encoding="utf-8") as f:
    json.dump(drugs_list, f, ensure_ascii=False, indent=2)

# Build relationships
rel = {
    "drug_atc": [],
    "alert_drugs": [],
    "study_drugs": [],
    "atc_consumption": [],
}
drug_id_map = {d["name"]: d["id"] for d in drugs_list}
for drug_name, atc_code in atc_drug_links:
    if drug_name in drug_id_map:
        atc_id = next(i+1 for i, a in enumerate(sorted(atc_codes)) if a == atc_code)
        rel["drug_atc"].append({"drug_id": drug_id_map[drug_name], "atc_code_id": atc_id})

# ATC-consumption links
d = json.load(open("frontend/public/data/consumption.json", encoding="utf-8"))
for r in d:
    code = r.get("atc_code")
    if code:
        rel["atc_consumption"].append({
            "atc_code": code,
            "consumption_record_id": r.get("id", 0),
            "drug_name": r.get("drug_name"),
            "year": r.get("year"),
            "geography": r.get("geography"),
        })

with open(out / "relationships.json", "w", encoding="utf-8") as f:
    json.dump(rel, f, ensure_ascii=False, indent=2)

print(f"ATC codes: {len(new_atc)}")
print(f"Drugs: {len(drugs_list)}")
print(f"Drug-ATC links: {len(rel['drug_atc'])}")
print(f"ATC-consumption links: {len(rel['atc_consumption'])}")

# Copy to frontend
import shutil
for fn in ["atc.json", "drugs.json", "relationships.json"]:
    shutil.copy(out / fn, Path("frontend/public/data") / fn)

print("\nDone! Files updated in both processed/public/ and frontend/public/data/")
